# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  deploy:
      runs-on: ubuntu-latest
      needs: test

      steps:

        - name: Heroku Auto Deployment
          # You may pin to the exact commit or the version.
          # uses: ElayGelbart/Heroku-Auto-Deployment@714f7d7da9749f34ce2771c8ea1d665c9130509c
          uses: ElayGelbart/Heroku-Auto-Deployment@v1.0.7
          with:
            # Name of the heroku application to which the build is to be sent.
            herokuAppName: app.py
            # Heroku API key
            herokuApiKey: 23c3a0b7-e3de-49d4-807d-8fe85a1865bc




